<?php defined('_ROOT') or die('Not Allowed');
$merge_block = 8;
$_tpl = '﻿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	Website generated by CMS v02
	URL: http://demo.phpbasic.com
	Email: w2ajax@gmail.com
-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />


<link rel="stylesheet" type="text/css" href="../template/Default/style/font-awesome-animation.min.css" media="all"/>
<link rel="stylesheet" href="template/css/font-awesome.css" type="text/css" media="all"/>
<link rel="stylesheet" type="text/css" href="template/css/main.css" />
<link rel="stylesheet" type="text/css" href="../template/Default/style/all.css" />
<link rel="icon" href="../favicon.ico" type="image/x-icon" />
<link rel="stylesheet" type="text/css" href="../template/Default/style/colorbox.css" media="all"/>

<title>CMS - '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</title>       
<script>var token  = \''.(isset($this->_data["."][0]['token'])?$this->_data["."][0]['token']:'').'\';</script>
<!--<script type="text/javascript" src="../plugins/jquery-1.11.1.min.js"></script>-->
<script type="text/javascript" src="../plugins/jquery-1.3.2.min.js"></script>

<script type="text/javascript" src="../template/Default/js/jquery.form.min.js"></script>
<script type="text/javascript" src="../template/Default/js/jquery-3.6.0.min.js"></script>


<script>var plugins_dir = \'../\';var root_dir = \''.(isset($this->_data["."][0]['root_dir'])?$this->_data["."][0]['root_dir']:'').'\'; var lang = \''.(isset($this->merge['system']['lang'])?$this->merge['system']['lang']:'').'\';</script>
<script type="text/javascript" src="../plugins/tableorder/jquery.tableorder.js"></script>
<script type="text/javascript" src="template/js/common.js"></script>
<script type="text/javascript" src="template/js/main.js"></script>
<script type="text/javascript" src="template/js/module.configure.js"></script>

<script type="text/javascript" src="../plugins/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="template/js/editor.js"></script>

<script type="text/javascript" src="../plugins/ckeditor/ckeditor.js"></script>
 <script type="text/javascript" src="../template/Default/js/2.3.1_picturefill.min.js"></script>
<script type="text/javascript" src="../plugins/divbox/divbox.js"></script>
<script type="text/javascript" src="../template/Default/js/jquery.colorbox-min.js"></script>
 
<link rel="stylesheet" href="../plugins/divbox/css/frontend.css" type="text/css" media="screen" />
<script type="text/javascript">
// var access_new = \''.(isset($this->merge['access']['new'])?$this->merge['access']['new']:'').'\';
// var access_edit = \''.(isset($this->merge['access']['edit'])?$this->merge['access']['edit']:'').'\';
// var access_delete = \''.(isset($this->merge['access']['delete'])?$this->merge['access']['delete']:'').'\';
</script>
<script type="text/javascript" src="../plugins/validate/validate.js"></script>
<link rel="stylesheet" href="../plugins/validate/css/validate.css" type="text/css" media="screen" />

<script type="text/javascript" src="../plugins/dateinput/dateinput.js"></script>
<!--<script type="text/javascript" src="../plugins/jquery.slug.js"></script>-->
<script type="text/javascript">
$(document).ready(function(){
	$.each($(\'form input[type=text]\'),function(i,val){
		var id = $(val).attr(\'name\');	
		id = id.replace("[","_");
		id = id.replace("]","");
		if($(val).attr(\'id\') == "" || $(val).attr(\'id\')  == undefined){
			$(val).attr(\'id\',id);
			$(val).addClass(id);
		}
	});
	//$("#name_vn").slug();
	
});
</script>

<script type="text/javascript">
$(document).ready(function(){
	$(".mtitle_vn").attr(\'maxlength\',\'60\');
	$(".mdesc_vn").attr(\'maxlength\',\'300\');
	$(\'.view_vn\').css({backgroundColor:"#fcebac"});
	$(\'.name_seo_vn\').css({backgroundColor:"#dadada"});	
});
</script>


<script type="text/javascript" src="template/skins/default/js/common.js"></script>
<link rel="stylesheet" type="text/css" href="template/skins/default/css/style.css" />
<!--[if IE]>
<style type="text/css">
tr.show{ display: block; }
</style>
<![endif]--> 

</head>
<body>
	
<div class="wrapper">
	<div class="container">
		<div class="hd">
			<ul class="hd-r">
			<li class="li"><a  class="hd-profile" href="javascript:void(0)"><i class="fa-solid fa-user"></i></a>
				 		<ul class=" profile">
                            <li> 
								<div class="logo_profile">T</div>
								<div class="info_profile">
									<strong>'.(isset($this->merge['login_user']['name_taixe'])?$this->merge['login_user']['name_taixe']:'').'</strong>
									<p>Tài xế xe: '.(isset($this->merge['login_user']['biensoxe'])?$this->merge['login_user']['biensoxe']:'').'</p>
								</div>
							</li>
							
                            <li class="br-fix2" style="clear:both"> 
								<div class="logout"><a href="?mod=user&act=logout" style="cursor: pointer;">Đăng xuất</a>
								</div>
								<div class="change_pass"><a href="?mod=user&act=reset" class="hd-resetPass">Đổi mật khẩu?</a></div>
							
							</li>
                        </ul>
				
				</li>
				<li class="li"><a  class="hd-" href="?mod=luongtaixe&act=v&code='.(isset($this->merge['login_user']['id_security'])?$this->merge['login_user']['id_security']:'').'">Lương</a> </li>
				<li class="li"><a >Lệnh</a> </li>
				<li class="li"><a  ><i class="fa-solid fa-bell br-white"></i></a> </li>
				
			</ul>
			<a class="hd-logo" href="./"><img src="template/skins/default/images/logo1.jpg" alt="logo" ></a>
		</div>
		
		<div class="ct">
			
			
			<div class="main">
				<div class="mainInner">
							
					
    <div class="page">
    <div class="container">
     <div class="back">
                 <a href="javascript:void(0)" onclick="history.go(-1)"><i class="fa-solid fa-arrow-left"></i> Back</a>
            </div>
        <div class="thongbao">
            <h3>THÔNG BÁO</h3>
            <strong>Chủ đề: </strong><p>'.(isset($this->merge['notification']['title'])?$this->merge['notification']['title']:'').'</p>
            <strong>Nội dung: </strong>
            <div class="content"><p>'.(isset($this->merge['notification']['content'])?$this->merge['notification']['content']:'').'</p></div>
            <strong>Tệp đính kèm: </strong>
            <table>  
                <tbody>
                   '.(isset($this->merge['notification']['file'])?$this->merge['notification']['file']:'').'
                </tbody>
            </table>
        </div>
    </div>
    </div>

				</div>			
			</div>
		</div>
		
		<div class="ft">
			<ul>
				<li><a href="/apptaixe/"><i class="fa-solid fa-house"></i><br>Home</a></li>
				<li><a href="javascript:void(0)" onclick="window.location.reload(true);"><i class="fa-solid fa-arrows-rotate fa-spin"></i><br>Làm mới</a></li>
				<li><a><i class="fa-sharp fa-solid fa-magnifying-glass"></i><br>Tra cứu</a></li>
				<li class="fix"><a  href="?mod=notification&act=view"><i class="fa-solid fa-bell"></i><br>Thông báo</a></li>
			</ul>
		</div>
	</div>
</div>

<table width="5" height="100%" cellpadding="0" cellspacing="0" border="0" class="btn_expandMenu"><tr><td>&nbsp;</td></tr></table>


<div class="cms_overlay"></div>
<div class="div-beforeSuccess">
    <div class="div-beforeSuccess_popup">
        <img src="template/images/loading.gif" alt="loading">
        <h4>Đang xử lý!!!</h4>
    </div> 
</div>
<div class="div-Success ">
    <div class="div-Success_popup">
        <img src="template/images/icon-success.png" alt="success">
        <h4>Thành công!!!</h4>
    </div> 
</div>
<div class="div-fail">
    <div class="div-fail_popup">
        <img src="template/images/error1.png" alt="error1">
        <h4>Xảy ra lỗi !!!</h4>
    </div> 
</div>

<noscript>
	<style type="text/css">
		.wrapper{ display: none; }
	</style>
	<div class="noscript">JavaScript must be enabled in order for you to use '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').' CMS. Please enable JavaScript by changing your browser options, then press <strong>F5</strong> to load page</div>
</noscript>


</body>
</html>'; ?>